[package]
name = "terrain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorous = "1.0.12"
delaunator = "1.0.2"
itertools = "0.11.0"
nannou = "0.18.1"
ordered-float = "4.1.0"
